In [99]:
import cv2
import numpy as np
import math
import colorsys

In [100]:
#ランダムで座標と値を発生
#本番はリストで受け取るので、この関数は不要
def getRandom2DPoints(width, height, n):
    x = np.random.randint(0, width, n)
    y = np.random.randint(0, height, n)
    temp = np.random.randint(-10, 45, n)

    pts = np.stack([x, y, temp], axis=1) 
    return    pts

In [101]:
def get_color2(a1,a2,a3):
    #平均値を求める
    ave = (a1+a2+a3)/3
    r = ave*5
    g = 0
    b = (50-ave)*5
    
    return(r,g,b)

In [102]:
def DelaunayDiagram(imgd, subdiv,array):
    height, width = imgd.shape[:2]

    # ドロネーの三角形
    triangles = subdiv.getTriangleList()
    pols = triangles.reshape(-1, 3, 2)
    inner_pts = np.empty((0, 3, 2))
    
    for pa in pols:
        # フレーム外の点は除外
        cnt = 0
        for p in pa:
            if p[0] < 0 or width <= p[0] :
                break
            if p[1] < 0 or height <= p[1] :
                break
            cnt += 1
        # フレーム内の点は有効
        if cnt == 3:
            inner_pts = np.append(inner_pts, [pa], axis=0)
    
    #rgb値を格納する配列を作成
    color_list = np.zeros((len(inner_pts),3))
    
    #3値を渡して色を設定
    for i in range(len(inner_pts)):
        color_list[i]=get_color2(array[(int)(inner_pts[i][0][0])][(int)(inner_pts[i][0][1])],array[(int)(inner_pts[i][1][0])][(int)(inner_pts[i][1][1])],array[(int)(inner_pts[i][2][0])][(int)(inner_pts[i][2][1])])
    
    #図形の描画
    for i in range(len(inner_pts)):
        #三角形の描画
        cv2.fillPoly(imgd, [inner_pts[i].astype(int)], color_list[i], 1)
        #三角形の辺の描画
        cv2.line(imgd,(inner_pts[i][0][0].astype(int),inner_pts[i][0][1].astype(int)),(inner_pts[i][1][0].astype(int),inner_pts[i][1][1].astype(int)),(0,0,0))
        cv2.line(imgd,(inner_pts[i][1][0].astype(int),inner_pts[i][1][1].astype(int)),(inner_pts[i][2][0].astype(int),inner_pts[i][2][1].astype(int)),(0,0,0))
        cv2.line(imgd,(inner_pts[i][2][0].astype(int),inner_pts[i][2][1].astype(int)),(inner_pts[i][0][0].astype(int),inner_pts[i][0][1].astype(int)),(0,0,0))

In [103]:
def main():
    width = 320
    height = 240
    
    #点の生成
    pts = getRandom2DPoints(width,height,50)
    print(pts)
    #白紙を作る
    img = np.full((height, width, 3), 255, np.uint8)
    
    rect = (0, 0, width, height)
    subdiv = cv2.Subdiv2D(rect)

    #(x1,y1,a1)の時、array[x1][y1]=a1とする
    array = np.zeros((width,height))
    print(array)
    
    for p in pts:
        subdiv.insert((int(p[0]), int(p[1])))
        array[p[0]][p[1]] = p[2]
        
    DelaunayDiagram(img, subdiv,array)

    for p in pts:
        #color = p[2]
        cv2.circle(img, (p[0],p[1]), 4, (0, 0, 0), thickness=-1, lineType=cv2.LINE_AA)
   
    cv2.imwrite('test2.png', img)

In [104]:
if __name__ == '__main__':
    main()

[[172 223  27]
 [125 118  16]
 [ 74 117  21]
 [198  13  -6]
 [ 92 103  12]
 [123  73  -6]
 [129 163  37]
 [105 166 -10]
 [257 109  18]
 [ 62  98  33]
 [136  10  12]
 [276 119  20]
 [ 27 205  -4]
 [304 112  44]
 [123  61  19]
 [156 178  -4]
 [316 156  -3]
 [280 136  14]
 [115 233  -8]
 [319  39  28]
 [310 152   1]
 [156 230  27]
 [248 195  27]
 [219 238   0]
 [  3 177  43]
 [ 67 103  39]
 [ 79  57   8]
 [ 80 231  18]
 [107 120   1]
 [118 235  29]
 [145   3  27]
 [ 96 221   1]
 [224 128  -9]
 [ 15  31   9]
 [ 65 172  15]
 [237 228  18]
 [112 200  11]
 [138  42  33]
 [226 168  43]
 [227  24  19]
 [204  79  -1]
 [216 237  15]
 [ 12  59  17]
 [265 233  29]
 [ 80 176  29]
 [ 58 197  39]
 [274  51  27]
 [307  61  25]
 [ 84 203  37]
 [218 170   6]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
